name: Deploy to the Janky server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - name: Send files to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "build/"
          target: ${{ secrets.REMOTE_TARGET }}
          overwrite: true
          strip_components: 1
